### ISSUE TITLE
Add a logout link to the navbar 

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#12]
The Logout link must submit a post request to the "logout/" url, something like: 

```
<form id="logoutForm" method="post" action="{% url 'users-logout' %}">
    {% csrf_token %}
</form>
<li class="side-nav-item">
    <a href="javascript:void(0);" class="side-nav-link" onclick="submitLogoutForm()">
        <i class="ri-logout-box-line"></i>
        <span> Logout </span>
    </a>
</li>
```

And the JS in the submitLogoutForm() will look something like this: 

```
<script>
    function submitLogoutForm() {
        // Get the form element
        var form = document.getElementById('logoutForm');

        // Submit the form
        form.submit();
    }
</script>
```

Alternatively, if you want to dodge the JS you can make it a button of submit type instead of a link. The choice is yours.

**Comment by Khumbolawo** [comment]
Done. Logout view shows the user they've been logged out and gives links to either sign up or log back in. Added the url to all the base templates and tested the logic for all 3 user types. Works

**Comment by Khumbolawo** [comment]
Issue resolved with pull request
