### ISSUE TITLE
Implement Prescription Business Logic

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#15]
- [x] 1.  Doctor should be able to create a prescription
- [x] 2.  Prescription should have code automatically generated.
- [ ] 3.  Doctor should be redirected to a table showing his assigned prescriptions
- [x] 4.  Code must be sent to Patient via SMS
- [ ] #39

**Comment by Victor-M16** [comment]
1. done
2.  done

**Comment by Khumbolawo** [comment]
I dunno if this form's permissions are working for a doctor user because as a doctor account I cannot the prescription route in the api and the form isn't working for me. I have all the latest changes on this branch

**Comment by Khumbolawo** [comment]
Fixed it by adding doctor and admin to the prescriptions viewset. it was set to pharmacist only

**Comment by Khumbolawo** [comment]
Hmm, prescriptions form looks like its still WIP on your end, so I'll discard changes on my branch for now. Just to report, this is what its doing:

1. Data is being sent to the api 
2. There is no console log of the data object in the console despite the code working
3. My custom success message that shows right below the form after that console log isnt showing (tested this with the other forms and it works)

**Comment by Khumbolawo** [comment]
Fixed it. Code still isn't being automatically created on my end though
