### ISSUE TITLE
Doctor home page prescription tables

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#41]
- [x] The tables must be scrollable, vertically
- [x] The table data must be sorted in order of 'updated_at' attribute
- [x] Optional: implement pagination (might take a while, do not prioritise over hardware). Try to do this without touching the backend API code, as this will break other features like the list dropdowns if done that way.

**Comment by Khumbolawo** [comment]
Latest merge has table changes

**Comment by Victor-M16** [comment]
Nice work on the table and sorting.

**Comment by Victor-M16** [comment]
The tables seem a bit fluky. I don't know if its the ajax request to the API but they aren't working as expected, the bottom one (prescription medication table ) is consistent while the top one is not) need to look into this
