### ISSUE TITLE
Landing page required.

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#43]
- [x] 1. Need the root url to not be the login screen but rather a landing page that describes the system. It will have a picture of the prototype, and us when completed.
- [x] 2. feel free to get some inspiration from various websites.
- [x] 3. Need some assets. The MUBAS logo and QECH logo should appear on the landing page. 
- [x] 4. Create our own or use the MUBAS logo as the favicon. If created, it must also show up on the landing page together with the other two logos.
- [x] 5. The login screen on mobile view has no heading maybe its just my phone, but it seems to be unique to that page

**Comment by Khumbolawo** [comment]
Done
