### ISSUE TITLE
The tables seem a bit fluky. I don't know if its the ajax request to the API but they aren't working as expected, the bottom one (prescription medication table ) is consistent while the top one is not) need to look into this

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#49]
The tables seem a bit fluky. I don't know if its the ajax request to the API but they aren't working as expected, the bottom one (prescription medication table ) is consistent while the top one is not) need to look into this

_Originally posted by @Victor-M16 in https://github.com/Victor-M16/Smart-Pharmacist/issues/41#issuecomment-2345019307_

**Comment by Khumbolawo** [comment]
Problem was some of the api routes not being correct since we changed the overall routing for the rest of the site when the landing page came in. Fixed it
