### ISSUE TITLE
Populate the database with medications

### ISSUE THREAD

**Issue by Victor-M16** [Victor-M16/Smart-Pharmacist#59]
Select 6 of the most commonly prescribed medications at QECH and assign them to the slots

**Comment by Khumbolawo** [comment]
Adding the following from doctor Chisomo's recommendation 

Painkillers
1. paracetamol
2. ibuprofen

Antibiotics
1. Amoxicillin
2. Cotrimoxazole (bactrim)
3. Erythromycin

Anti-hypertensives
1. Hydrochlorothiazide
2. Furosemide
3. Spinorolactone

Doctor Chisomo is finding me some market versions of some of these as of right now

**Comment by Khumbolawo** [comment]
Added them on vending slots. Closing this issue
